[data]
db_path = ""
table_name = "ci"

col_date_start = "dtest"
col_date_end = "dfinisol"
col_role = "role"
col_institution = "instit_nom"
col_location = "instit_loc"


[plugins]
data_loader = [
    "emsapp.data.loaders.access_loader",
    "emsapp.data.loaders.excel_loader",
]
