[data]
db_path = ""
table_name = "ci"

excel_start_year = 1900

col_date_start = "dtest"
col_date_end = "dfinisol"
col_role = "role"
col_institution = "instit_fullid"
col_institution_type = "instit_type"
col_location = "instit_loc"

date_formats = ["%x", "%d.%m.%Y", "%d/%m/%Y"]

last_selected = ""

[plot]
show_periods_info = true
show_today = false
legend_loc = "top"
plot_height = 10.2
plot_width = 24.3
show_everything = true
date_start = "2021-10-01"
date_end = "2022-04-01"

[plugins]
data_loader = [
    "emsapp.data.loaders.access_loader",
    "emsapp.data.loaders.excel_loader",
]
