# FILTRES ---------------------------------------------------------------------

[filter.ems_only] # Conserve uniquement les entrées concernant les EMS
type = "include"
column = "institution_type"
value = "EMS"

[filter.no_other_staff] # Rejète les entrées concernant les Collaborateurs autre
type = "exclude"
column = "role"
value = "Collaborateur autre"

# SÉPARATEURS -----------------------------------------------------------------
[splitter.district] # Sépare les entrées en fonction du district
type = "value"
column = "district"

[splitter.instit] # Sépare les entrées en fonction de l'institution
type = "value"
column = "institution"

[splitter.role] # Sépare les entrées en fonction du rôle 
type = "value"
column = "role"

# TRANSFORMATEURS -------------------------------------------------------------

[transformer.new] # Identifie les nouveaux cas
type = "new"

[transformer.cumulative] # Identifie combien de personnes sont en isolement chaque jour
type = "cumulative"

[transformer.periods] # Identifies les périodes de flambée potentielles
type = "periods"

# GROUPEURS -------------------------------------------------------------------

[grouper.institutions] # Crée un graphe par institution et rôle
splitter = ["instit", "role"]

[grouper.periodes_disctricts] # Crée un seul graphe pour toutes les périodes d'un district
splitter = ["role", "district"]
transformer = "periods"

[grouper.periodes_canton] # Crée un seul graphe pour toutes les périodes d'un district
splitter = ["role"]
transformer = "periods"

[grouper.districts] # évolution du nombre d'isolement par rôle et par district
splitter = ["role", "district"]
transformer = "cumulative"
